# syntax=docker/dockerfile:1
FROM ubuntu:22.04

# arguments
ARG NAME=libra
ARG UID
ARG GID

# pre-requisites
RUN apt-get update
RUN apt-get install -y \
    build-essential cmake ninja-build \
    git subversion curl python3 \
    m4 flex bison bc cpio libtool libtool-bin \
    libncurses-dev libssl-dev libelf-dev

# install Rust
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs -o rustup.sh
RUN chmod +x rustup.sh
RUN ./rustup.sh -y

# prepare environment
ENV DOCKER=1

# setup user
RUN groupadd -g ${GID} ${NAME}
RUN useradd -m -u ${UID} -g ${GID} -s /bin/bash ${NAME}
USER ${NAME}
